version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=your-secret-key
    volumes:
      - .:/app
    command: ['yarn', 'start']
